services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  web:
    build: .
    command: bash -c "python mysite/manage.py makemigrations; python mysite/manage.py migrate; python mysite/manage.py createsuperuser --noinput --username ${USERNAME} --email ${EMAIL} --password ${PASSWORD}; python mysite/manage.py runserver 0.0.0.0:8000;"
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - SECRET_KEY=${SECRET_KEY}
      - USERNAME=${USERNAME}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}