# Generated by Django 4.2 on 2025-02-24 16:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0038_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cloudinary_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cloudinary_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
